### PR TITLE
Add example-applications repository

### PR DESCRIPTION
**Pull request by k-gostev**
Add example-applications repository

### CODE REVIEW

**Review by netomi — APPROVED** [review]

**Comment by netomi** [comment]
While checking your project, I have seen that all repos have secret scanning disabled. Would you be ok to enable that for all repos? I can create the PR for you to approve.

**Comment by netomi** [comment]
repo has been created.

**Comment by k-gostev** [comment]
tanks @netomi ! We will evaluate the repositories with the other committers and will handle the changes alongside with https://github.com/eclipse-kanto/.eclipsefdn/issues/1

**Comment by netomi** [comment]
ty, here is a link to a project where we just recently added a consistent branch protection rule to all repos: https://github.com/eclipse-cdt-cloud/.eclipsefdn/blob/main/otterdog/eclipse-cdt-cloud.jsonnet

That might be helpful for you when setting it up for your project. The settings will probably vary. You can also use the playground at https://eclipse-kanto.github.io/.eclipsefdn/playground/ to sketch rules that are suited for your project.

image

**Pull request merged**
