### PR TITLE
Add branch protection rules and secret scanning

### PR DESCRIPTION
**Pull request by k-gostev**
[#1] Adding branch protection rules and secret scanning

### CODE REVIEW

**Comment by netomi** [comment]
LGTM, in case you are interested you could take a look here: https://github.com/eclipse-set/.eclipsefdn/blob/main/otterdog/eclipse-set.jsonnet#L3

here they define a common rule that is going to be used in all repo.

**Comment by k-gostev** [comment]
Thanks @netomi, I have added a custom rule and removed the `secret_scanning="enabled` as it seems that `enabled` is the default value, so it does not make sense to set it explicitly again

**Comment by netomi** [comment]
looks very good, ty.

**Review by netomi — APPROVED** [review]

**Comment by netomi** [comment]
changes are live.

**Pull request merged**
